apiVersion: v1
kind: Service
metadata:
  name: quobyte-2
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: quobyte-0
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
